### PR TITLE
fix(frontend,backend): Make item image required

### PR DESCRIPTION
**Pull request by Strajk**
# Description

Make item image required

### CODE REVIEW

**Comment by ghost** [comment]
On it! I'll review the changes as soon as possible!

**Review by ghost — CHANGES_REQUESTED** [review]
I don’t think it’ll work. Make sure it passes all checks, and  only then you’ll be able to merge the PR.

**Review by ghost — APPROVED** [review]
Perfect Strajk! You're now able to merge the PR.

**Comment by Strajk** [comment]
@vanessa-cooper-1 

tenor-268301362

**Pull request merged**
